### ISSUE TITLE
amplitude: tracking of 'take survey' button does not work

### ISSUE THREAD

**Issue by xaverfleer** [raphaelschaad/Plus-Web#12]
on public/survey.html (and public/en/survey.html) the tracking does not seem to track click events (it does but only after coming back to the site by pressing the back button).

**Comment by raphaelschaad** [comment]
Can't reproduce. Tested with Chrome, Safari, and FF. Worked in all. @xaverfleer can you post your repro steps, and configuration, with which it fails?

**Comment by xaverfleer** [comment]
If you can see the events with segment, it's probably just the debugger that does not break.
If you can see the events with segment, that's fine; you can close the issue.

How I tested it:
1. open survey.html in Google Chrome
2. put a breakpoint on line 63 (in the segment instrumentation script
3. click "Take survey"
**Expected behavior:** breakpoint stops loading of the new page
**Actual behavior:** new page is immediately loaded

**Comment by raphaelschaad** [comment]
The events do come through to Segment.

I observe the same behavior on index.html -- nothing special for me for survey.html. And for you?

Is your expected behavior right? Should it really break there? I'm not entirely sure how `analytics.trackLink()` works under the hood but the line where we track the action really just *registers our intent to track and immediately returns*, right? When the registered link gets clicked, analytics.js tracks this together with the context we have passed earlier when registering the function. When you go back in your browser, what you're breaking on, I assume, is not the tracking but the re-registering of the tracking.

**Comment by xaverfleer** [comment]
You are absolutely right.

**Expected behavior:** Breakpoint has no effect
**Actual behavior:** Breakpoint has no effect

Thus the issue is invalid.

Thank you!
