### ISSUE TITLE
investigate adding browserslist

### ISSUE THREAD

**Issue by xaverfleer** [raphaelschaad/Plus-Web#29]
https://github.com/browserslist/browserslist

> You then specify what you want to support like this: https://github.com/aquasonic/Cocoon.BackOffice/commit/bbe17552b34bec9fb2416624e087b3b17265036f#diff-5406bad5d33e07742b5599e8ce48dade (edited)

**Comment by raphaelschaad** [comment]
What's the reason this issue is closed?

**Comment by xaverfleer** [comment]
In my understanding browserlist will be interesting, once we have a large amount of visitors so we
 - loose track of the browsers they use and 
 - want to increase performance by not compiling down to ES5

For now, there is no need, because we support full ES5 for IE11.

**Comment by raphaelschaad** [comment]
Is the idea of browserlist to codify the target browsers so tools can automatically warn you if you use unsupported features or do more targeted building? If yes, that would be great. Because right now we have [a note in the README on browser compatibility](https://github.com/raphaelschaad/Plus-Web#browser-compatibility), which isn't enforced and relies on us keeping it in our heads.

**Comment by xaverfleer** [comment]
Yes: browserlist allows more targeted building.

I do see value in adding the tool, but I think there are other things that are much more important for the moment e.g. netlify dev.

I closed the issue, for keeping the issues cleaner, but we can re-add it, if you prefer.

**Comment by raphaelschaad** [comment]
I'd hope we find a better way to indicate the priority of an issue than its 'open' vs. 'closed' state.

**Comment by xaverfleer** [comment]
#26 will add Browserslist

**Comment by xaverfleer** [comment]
#26 adds Browserslist
