### ISSUE TITLE
Address CORB: "Cross-Origin Read Blocking (CORB) blocked cross-origin response <URL> with MIME type text/html"

### ISSUE THREAD

**Issue by xaverfleer** [raphaelschaad/Plus-Web#42]
### How to reproduce:
load `plus.healthcare` in Google Chrome

**Comment by raphaelschaad** [comment]
Can't reproduce. Can you reproduce it when opening your Chrome in Incognito Mode?

**Comment by xaverfleer** [comment]
I can reproduce it on my windows computer:
![CORB](https://user-images.githubusercontent.com/7235734/60529820-b5a73480-9cf7-11e9-9141-5a9a581c9128.png)

environmen: Google Chrome version 75.0.3770.100, incognito mode, windows 10

**Comment by xaverfleer** [comment]
As I understood it, it is no big deal:
- the issue: [Spectre (security vulnerability)](https://en.wikipedia.org/wiki/Spectre_(security_vulnerability)) mitigation, browsers should not guess the type of any content, in our case 'text/javascript'
- solution: add the content type when loading JavaScript resources dynamically with XMLHttpRequest
- where to fix: fast.wistia.net/assets/external/engines/hls_video.js
- who can fix it: Wistia

I guess Wistia will fix it

If they do not fix it and it turns out to be important, we should consider to host the videos on our own

**Comment by xaverfleer** [comment]
I can reproduce it on my MacBook Pro with Google Chrome

**Comment by raphaelschaad** [comment]
I'm on MacBook Pro Google Chrome Version 75.0.3770.100 (Official Build) (64-bit) Incognito Mode on (just to avoid any extensions or such interfering) and now get it to (not sure why I wasn't getting it the first time I tried to reproduce). 
<img width="784" alt="Screen Shot 2019-07-03 at 17 56 36" src="https://user-images.githubusercontent.com/439447/60632698-f799ae80-9dbb-11e9-9d9e-2624b288ff2f.png">

Great analysis.
- If I understand correctly, specifying `text/javascript` in our pages won't help?
- Regardless of this issue, should we specify `text/javascript` on our pages? I omitted it because I thought it's "an old practice".
- Do you want to raise it with Wistia tech support?
Once we're done here and there's no action on our side, feel free to close this issue.

**Comment by xaverfleer** [comment]
> `text/javascript` in our pages won't help?

this is correct. In the HTML [5.2 specification](https://www.w3.org/TR/html52/semantics-scripting.html#the-script-element), W3C even recommends to omit `text/javascript`

> Authors should omit the attribute, instead of redundantly giving a JavaScript MIME type.

I will raise it with Wistia tech support. Since there is no hurry, I'll concentrate on the Babel task, and come back later.

For the record: my previous analysis seems to have been partially incorrect. For some reason the browser tries to download a `.ts` (TypeScript) file. This is probably a bug at Wistia (or possibly we use the API incorrectly)

**Comment by raphaelschaad** [comment]
I don't think we're using it wrong, or at least it wouldn't be a mistake we've introduced -- I've just copied the snippet they provided and have not altered it.

**Comment by xaverfleer** [comment]
I cannot reproduce the issue anymore. I guess Wistia has fixed it
